#+INCLUDE: ./doc_modern.org

* Torte salate
** Torta salata alla zucca e cime di rapa
***   Ingredienti

| Qt.           | Ingrediente                                        |
|---------------+----------------------------------------------------|
|               | pasta brise                                        |
| 250 gr. circa | polpa di zucca tagliati a pezzi di media grandezza |
| 400 gr. circa | cime di rapa                                       |
| 2             | uova                                               |
| 150 gr.       | formaggio caprino fresco/ricotta di capra o        |
| 2             | cucchiai di Grana Padano grattugiato               |
| 1 dl.         | di panna fresca                                    |
|               | noce moscata                                       |
|               | sale e pepe                                        |

***   Preparazione

Lessa la zucca al vapore senza esagerare nella cottura, la polpa non
deve disfarsi, quindi versa i pezzi di zucca cotti in un colino in modo
che perdano l'eventuale acqua in eccesso. Pulisci le cime di rapa e
togli i gambi più legnosi e cuocile al vapore per circa 8-10 minuti,
quindi passale velocemente sotto l'acqua corrente fredda per mantenere
il bel colore verde. In una ciotola lavora il formaggio con le uova ed
il Grana Padano grattugiato, aggiungi la panna, insaporisci con un po'
di noce moscata e aggiusta di sale e pepe e con una piccola frusta
amalgama bene fino ad ottenere una crema abbastanza liquida.

Sistema le le cime di rapa nella tortiera, direttamente sopra la pasta
brisée e alternale con i pezzi di zucca. Infine versa la crema in
maniera uniforme sopra le verdure e inforna a 200° per circa 30-40
minuti.

Se preferisci una versione più saporita cuoci la zucca in forno con gli
aromi che preferisci con un giro d'olio d'oliva e passa velocemente le
cime di rapa in padella con un po' di burro. Io ho preferito usare le
verdure cotte al vapore per rendere la torta salata più leggera. 
